name: Deploy ke InfinityFree
on:
  push:
    branches:
      - main  # Pastikan ini sesuai nama branch kamu (main/master)

jobs:
  FTP-Deploy-Action:
    name: Proses Upload FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Upload ke InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./htdocs/  # PENTING: Jangan hapus ./htdocs/
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/**